capabilityId: BWCE
version:
  - 1
  - 0
  - 0
recipe:
  helmCharts:
    - name: bwprovisioner
      namespace: tibco-dp-cir26d3hj3bpvpc0nmpg
      repository:
        git:
          host: https://github.com/abhide-tibco/tp-int.git
          path: /helm/charts/bwprovisioner
          branch: main
      values:
        - content: |
            global:
              bwprovisioner:
                data:
                  namspace: tibco-dp-cir26d3hj3bpvpc0nmpg
                image:
                  registry: reldocker.tibco.com
                  tag: 145
            ingress:
              annotations:
                haproxy.org/cors-enable: "true"
                haproxy.org/load-balance: leastconn
                haproxy.org/src-ip-header: X-Real-IP
                haproxy.org/timeout-http-request: 600s
                ingress.kubernetes.io/rewrite-target: /
                meta.helm.sh/release-name: bwprovisioner
                meta.helm.sh/release-namespace: tibco-dp-cir26d3hj3bpvpc0nmpg
              enabled: true
              hostsOverride: false
            volumes:
              bwprovisioner:
                persistentVolumeClaim:
                  create: true
                  storageClassName: standard
            config:
              SOURCE_REGISTRY: "reldocker.tibco.com"
      flags:
        install: true
        createNamespace: false
        dependencyUpdate: true
    - name: artifactmanager
      namespace: tibco-dp-cir26d3hj3bpvpc0nmpg
      repository:
        git:
          host: https://github.com/abhide-tibco/tp-int.git
          path: /helm/charts/artifactmanager
          branch: main
      values:
        - content: |
            global:
              artifactmanager:
                data:
                  namspace: tibco-dp-cir26d3hj3bpvpc0nmpg
                image:
                  registry: reldocker.tibco.com
                  tag: 24
            ingress:
              annotations:
                haproxy.org/cors-enable: "true"
                haproxy.org/load-balance: leastconn
                haproxy.org/src-ip-header: X-Real-IP
                haproxy.org/timeout-http-request: 600s
                ingress.kubernetes.io/rewrite-target: /
                meta.helm.sh/release-name: artifactmanager
                meta.helm.sh/release-namespace: tibco-dp-cir26d3hj3bpvpc0nmpg
              enabled: true
              hostsOverride: false
            volumes:
              artifactmanager:
                persistentVolumeClaim:
                  create: true
                  storageClassName: standard
      flags:
        install: true
        createNamespace: false
        dependencyUpdate: true
    - name: apiserver
      namespace: tibco-dp-cir26d3hj3bpvpc0nmpg
      repository:
        git:
          host: https://github.com/abhide-tibco/tp-int.git
          path: /helm/charts/apiserver
          branch: main
      values:
        - content: |
            global:
              apiserver:
                data:
                  namspace: tibco-dp-cir26d3hj3bpvpc0nmpg
                image:
                  registry: reldocker.tibco.com
                  tag: 7-m1-ext
            ingress:
              annotations:
                haproxy.org/cors-enable: "true"
                haproxy.org/load-balance: leastconn
                haproxy.org/src-ip-header: X-Real-IP
                haproxy.org/timeout-http-request: 600s
                ingress.kubernetes.io/rewrite-target: /
                meta.helm.sh/release-name: apiserver
                meta.helm.sh/release-namespace: tibco-dp-cir26d3hj3bpvpc0nmpg
              enabled: true
              hostsOverride: false
            ingressExternal:
              annotations:
                haproxy.org/cors-enable: "true"
                haproxy.org/load-balance: leastconn
                haproxy.org/src-ip-header: X-Real-IP
                haproxy.org/timeout-http-request: 600s
                ingress.kubernetes.io/rewrite-target: /
                meta.helm.sh/release-name: apiserver
                meta.helm.sh/release-namespace: tibco-dp-cir26d3hj3bpvpc0nmpg
              enabled: true
              hosts:
                - host: local
                  paths:
                  - path: /
                    pathType: Prefix
      flags:
        install: true
        createNamespace: false
        dependencyUpdate: true
        isDevTesting: false
    - name: distributed-lock-operator
      namespace: tibco-dp-cir26d3hj3bpvpc0nmpg
      repository:
        git:
          host: https://github.com/abhide-tibco/tp-int.git
          path: /helm/charts/distributed-lock-operator
          branch: main
      values:
        - content: |
            global:
              image:
                registry: reldocker.tibco.com
                tag: 58
      flags:
        install: true
        createNamespace: false
        dependencyUpdate: true
        isDevTesting: false
status: deployed
region: vagrant
tags:
  - Tag1
  - Tag2

