capabilityId: FLOGO
version:
  - 1
  - 0
  - 0
recipe:
  helmCharts:
    - name: flogoprovisioner
      namespace: tibco-dp-cir26d3hj3bpvpc0nmpg
      repository:
        git:
          host: https://github.com/abhide-tibco/tp-int.git
          path: /helm/charts/flogoprovisioner
          branch: main
      values:
        - content: |
            global:
              flogoprovisioner:
                data:
                  namspace: tibco-dp-cir26d3hj3bpvpc0nmpg
                image:
                  registry: reldocker.tibco.com
                  tag: 9
            ingress:
              annotations:
                haproxy.org/cors-enable: "true"
                haproxy.org/load-balance: leastconn
                haproxy.org/src-ip-header: X-Real-IP
                haproxy.org/timeout-http-request: 600s
                ingress.kubernetes.io/rewrite-target: /
                meta.helm.sh/release-name: flogoprovisioner
                meta.helm.sh/release-namespace: tibco-dp-cir26d3hj3bpvpc0nmpg
              enabled: true
              hostsOverride: false
            volumes:
              flogoprovisioner:
                persistentVolumeClaim:
                  create: true
                  storageClassName: standard
            config:
              SOURCE_REGISTRY: "reldocker.tibco.com"
      flags:
        install: true
        createNamespace: false
        dependencyUpdate: true
        isDevTesting: false
status: deployed
region: vagrant
tags:
  - Tag1
  - Tag2

